\newpage

\newcommand{\vectorproj}[2][]{\mathrm{proj}_{\vect{#1}}\vect{#2}}
\newcommand{\vectorcomp}[2][]{\mathrm{comp}_{\vect{#1}}\vect{#2}}
\newcommand{\vect}{\mathbf}
\newcommand{\R}{\mathbb{R}}

# Vectors
## Basics
**Reading: Stewart Chapter 12, Thomas Calculus Chapter 12,
  Active Calculus Chapter 9**

You should be able to answer the following questions after reading this section:

- What is a vector?

- What does it mean for two vectors to be equal?

- How do we add two vectors together and multiply a vector by a scalar?

- How do we determine the magnitude of a vector? 

- What is a unit vector 

- How do we find a unit vector in the direction of a given vector?

Typically, we talk about 3-dimensional vectors (as discussed in Stewart and Thomas).
However, since talking about $n$-dimensional vectors doesn't
require much more effort,
we will talk about $n$-dimensional vectors instead.

::: {.definition}
An $n$-dimensional Euclidean space $\mathbb{R}^n$ 
is the Cartesian product of $n$ Euclidean spaces $\mathbb{R}$.
:::

::: {.definition}
An $n$-dimensional vector $\textbf{v}\in \mathbb{R}^n$ is a tuple
\begin{equation}
    \textbf{v} = \langle v_1,\dots, v_n \rangle \,,
\end{equation}
where $v_i \in \mathbb{R}$.
:::


In dimensions less than or equal to 3, we represent a vector 
geometrically by an arrow, whose length represents the magnitude.

::: {.remark}
A point in $\mathbb{R}^n$ is also represented by an $n$-tuple 
but with round brackets.
A vector connecting two points $A= (a_1, \dots, a_n)$
and $B=(b_1, \dots, b_n)$ can be constructed as
\begin{equation*}
    \textbf{x} =  \langle b_1-a_1, \dots, b_n - a_n \rangle \,.
\end{equation*}

We denote the above vector as  $\vec{AB}$ where $A$ is the tail (initial point)
and  $B$ is the tip/head (terminal point).
We denote $\textbf{0}$ to be the zero vector, i.e.,
\begin{equation*}
    \textbf{0} = \langle 0, \dots, 0 \rangle \,.
\end{equation*}
:::


::: {.definition}
The length of a vector $\textbf{v}$ (denoted by $| \textbf{v}|$) is defined to be
\begin{equation}
    |\textbf{v}| = \sqrt{ v_1^2 + \dots + v_n^2} \,.
\end{equation}
:::

::: {.definition}
A unit vector is a vector that has magnitude 1.
:::

::: {.exercise}
Turn a vector $\textbf{v} \in \mathbb{R}^n$ into a unit vector with the same
direction.
:::

## Rules to manipulate vectors {-}

Let $\textbf{a}, \textbf{b} \in \mathbb{R}^n$ and $c,d \in \mathbb{R}$. Then,

\begin{equation*}
    c( \textbf{a} + \textbf{b}) = \langle c a_1 + c b_1, \dots, c a_n + c b_n \rangle  
    = c\textbf{a} + c\textbf{b} \,,
\end{equation*}
and
\begin{equation*}
 (c+d) \textbf{a} = c\vect{a} + d\vect{a} \,.
\end{equation*}

These formulas are deceptively simple. Make sure you understand all the implications.

Because of this rule, sometimes it is good to write vectors in terms of elementary vectors:
\begin{equation*}
    \vect{u} = u_1 \vect{e_1} + \dots + u_n \vect{e_n} \,,
\end{equation*}
where
$e_i = \langle 0,\dots, 1, \dots, 0\rangle$ is the vector which has zero at all entries
except that the  $i^{th}$ entry is 1.

In 3D,
\begin{equation*}
    \vect{e_1} = \vect{i} \,, \qquad 
    \vect{e_2} = \vect{j} \,, \qquad
    \vect{e_3} = \vect{k} \,.
\end{equation*}

## Properties of vector operations {-}

Read the book

(Make sure you understand the geometric intepretation)


##  Products
### Dot product
- How is the dot product of two vectors defined and what geometric information does it tell us?

- How can we tell if two vectors in $\mathbb{R}^n$
are perpendicular?

- How do we find the projection of one vector onto another?

::: {.definition}
The dot product of vectors $\textbf{u} = \langle u_1, \dots, u_n \rangle$
and $\textbf{v} = \langle v_1, \dots, v_n \rangle$ in $\mathbb{R}^n$ is the
scalar
\begin{equation*}
    \textbf{u} \cdot \textbf{v} = u_1 v_1 +\dots + u_n v_n \,.
\end{equation*}
:::

### Properties of dot product {-}
Let $\textbf{u}, \textbf{v}, \textbf{w} \in \mathbb{R}^n$. Then,

1. $\textbf{u}\cdot \textbf{v} = \textbf{v}\cdot \textbf{u}$,

2. $(\textbf{u} + \textbf{v})\cdot \textbf{w} = (\textbf{u}\cdot \textbf{w}) + (\textbf{v}\cdot \textbf{w})$,

3. If $c$ is a scalar, then $(c \textbf{u})\cdot \textbf{w} = c (\textbf{u}\cdot \textbf{w})$.

::: {.theorem name="Law of cosine"}
If $\theta$ is the angle between the vectors $\textbf{u}$ and $\textbf{v}$, then
   \begin{equation*}
        \textbf{u}\cdot \textbf{v} = |\textbf{u}|| \textbf{v}| \cos \theta \,.
   \end{equation*}
:::

::: {.corollary}
Two vectors $\textbf{u}$ and $\textbf{v}$ are orthogonal to each other
if $\textbf{u} \cdot \textbf{v} = 0$.
:::

### Projection {-}

Let $\textbf{u}, \textbf{v}\in \mathbb{R}^n$. The component of $\textbf{u}$ 
in the direction of $\textbf{v}$ is the scalar
\begin{equation*}
\vectorcomp[v]{u} = \frac{\vect{u}\cdot \vect{v}}{|\vect{v}|} \,,
\end{equation*}
and the projection of $\vect{u}$ onto $\vect{v}$ is the vector
\begin{equation*}
    \vectorproj[v]{u} 
    =\left( \vect{u}\cdot \frac{\vect{v}}{|\vect{v}|}\right) \frac{\vect{v}}{|\vect{v}|} 
    = \frac{\vect{u}\cdot \vect{v}}{\vect{v} \cdot\vect{v}} \vect{v} \,.
\end{equation*}

Read the book for more details.
Make sure you understand the geometric meaning.


### 3D special: Cross product
This concept is very specific to $\mathbb{R}^3$.
It will not make sense in other dimensions.

::: {.definition}
Let $\vect{a}, \vect{b} \in \mathbb{R}^3$.
The cross product of $\vect{a}$ and $\vect{b}$ is defined to be
\begin{equation*}
    \vect{a} \times \vect{b} = \langle a_2 b_3 - a_3 b_2, a_3b_1 - a_1 b_3, a_1b_2 - a_2b_1 \rangle \,.
\end{equation*}
:::

::: {.theorem}
Let $\theta$ be the angle between $\vect{a}$ and $\vect{b}$. Then,
\begin{equation*}
    | \vect{a} \times \vect{b} | = |\vect{a}||\vect{b}| \sin\theta \,.
\end{equation*}
:::

::: {.theorem}
The vector $\vect{a}\times \vect{b}$ is orthogonal to both $\vect{a}$ and $\vect{b}$.
:::
