\newpage
# Some basic equations in $\R^3$
Just to build some toy examples for the future, we will play with some basic
equations in three dimensions.

## Equations for lines

A line is a collection of points that is parallel to a vector and goes through a 
specific point.
To capture this idea, we have the following representation for a line
\begin{equation*}
    L = \{\vect{r}(t) \,|  \vect{r}(t) = \vect{r}_0 + t \vect{v}, t\in \R \}  \,,
\end{equation*}
where ${r}_0$ is the initial position and $\vect{v}$ is the direction.
The equation for $\vect{r}(t)$ is called a **vector equation for a line $L$**.

Let $\vect{v} = \langle v_1, v_2, v_3 \rangle$ and $\vect{r}_0 = ( x_0, y_0, z_0 )$.
The **parametric equations** of $L$ is the following system of equations

\begin{gather*}
    x = x_0 + v_1 t\,, \\
    y = y_0 + v_2 t\,, \\
    z = z_0 + v_3 t \,. 
\end{gather*}

This leads to the **symmetric equations** of $L$

\begin{equation*}
    \frac{x - x_0}{v_1} = \frac{y - y_0}{v_2} = \frac{z - z_0}{v_3} \,.
\end{equation*}


::: {.definition}
Two lines are parallel if their directional vectors are parallel (scalar multiple of each other).

Two lines that are not parallel and don't intersect each other are said to be skew.
:::

## Equations for planes

A plane is a collection of points that is perpendicular to one specific direction 
represented by a some vector called  a **normal vector**. 
Note that due to scaling, there are more than one normal vector.
To capture this idea, we have the following representation of a plane

\begin{equation*}
    P = \{ \vect{r} \, | \, \vect{n} \cdot (\vect{r}- \vect{r}_0 ) = 0 \} \,.
\end{equation*}

This is called a **vector equation for the plane $P$**.

Multiplying things out, we have the **scalar equation of the plane $P$** with 
normal vector $\vect{n} = \langle n_1, n_2, n_3 \rangle$ through a point $P_0(x_0, y_0, z_0)$
\begin{equation*}
    n_1(r_1- x_0) + n_2 (r_2 - y_0) + n_3(r_3 - z_0) = 0 \,.
\end{equation*}

The equation of the form
\begin{equation*}
    ax + by + cz + d = 0 
\end{equation*}
is called a **linear equation**.

::: {.definition}
Two planes are said to be parallel if their normal vectors are parallel.
If two planes are not parallel, they intersect in a straight line and
the angle between the two planes is defined to be the angle between the 
two normal vectors.
:::

## Cylinders

::: {.definition}
A cylinder is a surface that consists of all lines (called **rulings**) that
are parallel to a given line.
:::

::: {.example}
1. $z = x^2$
2. $x^2 + y^2 = 1$
:::

## Quadric surfaces

::: {.definition}
A quadric surface is the graph of a second-degree equation in three variables
$x,y$ and $z$. 
The equation that represents these surfaces is
$$Ax^2 + By^2 + Cz^2 + Dz = E\,.$$
:::

::: {.example}
1. Ellipsoid
   $$\frac{x^2}{a^2} + \frac{y^2}{b^2} + \frac{z^2}{c^2} = 1\,. $$

2. Hyperbolic paraboloid
   $$\frac{y^2}{b^2} - \frac{x^2}{a^2} = \frac{z}{c} \,.$$

3. Elliptical cone
   $$\frac{x^2}{a^2} + \frac{y^2}{b^2} = \frac{z^2}{c^2} \,.$$

Read the books for more surfaces and pictures.
:::


