\newpage

# Functions in higher dimensions


\textbf{Reading: Stewart Chapter 12, 13, Thomas Calculus Chapter 12, 13, Active Calculus Chapter 9}

## Functions of several variables

::: {.definition}
A function of several variables is a function
$f: D \to C$ where $D \subseteq \R^m$ and $C \subseteq \R^n$, where $m\geq 2$ and $n\geq 1$.
$$f({x}) = ( f_1(x_1,\dots, x_m),\dots, f_n(x_1,\dots, x_m)  ) \,.$$
$D$ is called the domain of $f$ and $C$ is called the codomain of $f$.
:::

The domain of $f$ is where each of the component $f_i$ of $f$ is defined.

::: {.example}
The following are some examples of multivariable functions

1. $f(x,y) = x^2 - 2xy + y^2$

2. $f(x,y,z) = \frac{1}{1 - xy^2}$
:::



## Vector functions

### Limit, continuity and differentiation

The expression in the vector equation for a line is an example of a function that maps from $\R$ to $\R^n$.
There's no one who would stop us from considering more general kinds of function.

::: {.definition}
A **vector function** (**vector-valued function**) is a function that has the codomain that belongs to $\R^n$ where $n\geq 2$. In other words, $f: D  \to \R^n$.
:::

::: {.example} 
The following are some examples of vector functions.

1. $\vect{r}(t) = \vect{r}_0 + t\vect{v}$

2. $\vect{f}(t) = \langle \cos(t),\sin(t), t \rangle$
:::

Note that my definition is more general than that in the book.
However,
**In this course, whenever we talk about vector valued function, we will only refer to 
that which has one dimensional domain ($D \subseteq \R$).**

By and large, there's nothing different between a vector function and
a one-variable scalar function.
All the concepts such as limit, continuity and differentiability are applied 
to each coordinate the same way as in one dimensional case.

::: {.theorem}
Let $\vect{r}: \R \to \R^n$, given by $\vect{r}(t) = \langle r_1(t), \dots , r_n(t) \rangle$.
Then, $\vect{r}$ is said to be continuous at $t_0$ if
\begin{equation*}
    \vect{r}(t_0) = \lim_{t\to t_0} \vect{r}(t) \,,
\end{equation*}
where
\begin{equation*}
    \lim_{t\to t_0} \vect{r}(t) = \langle \lim_{t\to t_0}r_1(t) , \dots , \lim_{t\to t_0} r_n(t) \rangle \,. 
\end{equation*}
Furthermore, we can define the derivative of $\vect{r}$
\begin{equation*}
    \frac{d}{dt} \vect{r}(t) = \vect{r}'(t) = \lim_{h\to 0} \frac{\vect{r}(t+h) - \vect{r}(t)}{h} 
\end{equation*}
if this limit exists.
:::

When $\vect{r}:I \to \R^n$ ($I$ is an interval in $\R$) is continuous,
we call it a **space curve** (to describe the intuitive picture of what
a curve should look like in our mind).

Geometrically, if $\vect{r}'(t)$ exists and $\vect{r}'(t) \not= \vect{0}$, it
represents the **tangent vector** of the curve $\vect{r}$ at $t$.

::: {.definition}
A **parametric equation** for a curve is an equation of the form
$$
x=x(t)\,, \quad  y = y(t)\,, \quad z = z(t) \,.
$$
:::


Typical differentiation rules apply.

::: {.theorem name="Differentiation rules"}
1. $(\vect{u}(t) + \vect{v}(t))' = \vect{u}'(t) + \vect{v}'(t)$

1. $(c \vect{u}(t))' = c \vect{u}'(t)$

1. $(f(t) \vect{u}(t))' = f'(t) \vect{u}(t) + f(t) \vect{u}'(t)$

1. $(\vect{u}(t) \cdot \vect{v}(t))' = \vect{u}'(t)\cdot \vect{v}(t) + \vect{u}(t)\cdot \vect{v}'(t)$

1. $(\vect{u}(t) \times \vect{v}(t))' = \vect{u}'(t)\times \vect{v}(t) + \vect{u}(t)\times \vect{v}'(t)$

1. $(\vect{u}(f(t)))' = \vect{u}'(f(t)) f'(t)$
:::


### Integrals
There are different ways to play with integrals for vector functions, 
each has its own interpretation and physical applications.

#### Indefinite integral
\begin{equation*}
    \int_a^b \vect{r}(t) \, dt = \left\langle \int_a^b r_1(t) \, dt, \int_a^b r_2(t) \, dt, \int_a^b r_3(t) \, dt \right\rangle
\end{equation*}

#### Arc Length and curvature

::: {.definition}
The length the curve $\vect{r}:[a,b] \to \R^n$ is defined to be
\begin{equation*}
L = \int_a^b \left| \vect{r}'(t) \right| \, dt \,.
\end{equation*}
:::

If one wants to keep track the length of the curve  $\vect{r}:[a,b] \to \R^n$ made by an airplane
at any time $t$, one uses the **arc length function**

\begin{equation*}
    \ell(t) = \int_a^t \left| \vect{r}'(u) \right| \, du \,.
\end{equation*}


#### Re-parametrize with respect to arc length {-}

The nice thing about $\ell(t)$ is that it is a strictly increasing function with respect to $t$,
given that $\vect{r}'$ is non-zero for all $t$.
Therefore, letting $s = \ell(t)$, we can talk about the inverse of $\ell$, $\ell^{-1}:[0,L] \to [a,b]$
\begin{equation*}
    t = \ell^{-1}(s) \,.
\end{equation*}
Therefore, we can re-write
\begin{equation*}
\vect{r}(t) = \vect{r}(\ell^{-1}(s)) \,.
\end{equation*}

::: {.theorem}
$$\left| \frac{d r(t)}{ds} \right| = 1 \,.$$
Thus,
$$l(s) = \int_0^s \left| \frac{d}{ds} \vect{r}(t) \right| \, dt = s \,.$$
:::

Because of the unchanging nature of the arc-length (with respect to the
parametrization),
it is used to define a geometric quantity of a space curve called __curvature__.

::: {.definition name="curvature"}
Let $\vect{T}(t)$ be the unit tangent vector of the curve $\vect{r}:[a,b] \to \R^3$.
The curvature of $\vect{r}(t(s))$ is defined to be
\begin{equation*}
    \kappa(s) = \left| \frac{d \vect{T}(t(s))}{ds}\right| \,.
\end{equation*}
:::

To convert this into the parameter $t$, we write $s= s(t)$ and use chain rule
to get.

::: {.theorem}
We have that
\begin{equation*}
    \kappa(s(t)) =  \frac{|\vect{T}'(t)|}{|\vect{r}'(t)|}   \,.
\end{equation*}
:::

### Space curve in $\R^3$ and motion in space

Read the book. This part is not required but it is so beautiful, you may want to read it
as an exercise at home (to test how much you understand what we've been discussing so far).

## Activity: on osculating circle and curvature

For those who are interested in the geometrical meaning of the curvature without having
to accept from the book that the curvature is the inverse of the radius of the osculating circle,
please take a look at [https://github.com/sonv/MultiCalc/blob/main/Writing/latexbuild/osculating.pdf](https://github.com/sonv/MultiCalc/blob/main/Writing/latexbuild/osculating.pdf).

