
# Syllabus {-}

### Key information {-}

* Instructor: Truong-Son Van 
* Email: [son.van+104@fulbright.edu.vn](mailto:son.van+104@fulbright.edu.vn)
* Class time: Mon&Wed 9:45-11:15AM 
* Class Location: Classroom 1 
* Office hours: M & W: 3-4PM, T & Th: 10-11AM 
* Prerequisites: Calculus (MATH 101)
* TA: Tran Lan Phuc, [phuc.tran.200077@student.fulbright.edu.vn](mailto:phuc.tran.200077@student.fulbright.edu.vn)
* TA office hours: M & F: 2-3PM

## HOW THIS COURSE WILL FUNCTION {-}

This course is going to be very different from what you have been used to with math classes before.
You are expected to do preparation work at home before coming to class.
Here's the break down of the process:

1. At home: Students watch assigned YouTube videos from [Prof. Rob Ghrist of the University of Pennsylvania](https://www2.math.upenn.edu/~ghrist/BLUE.html).
   a. While watching, it is important that you take notes of concepts you don't understand.
   b. (Optional) Try to read in the textbooks/notes about the concepts you don't understand.

2. In class: 
   a. Prof. Son will go through the concepts that you don't understand on the board.  
   b. You will work through worksheets and together with Prof. Son, you will learn how to solve problems.

## Materials and references  {-}
No textbook is required. We will follow the University of Pennsylvania's guide
(https://www.amazon.com/Calculus-Blue-Guide-Robert-Ghrist/dp/1944655077/).
However, a physical copy of this book is not required.

### Required materials {-}

- YouTube videos from the Calculus BLUE series of user Prof Ghrist Math:

    1. First Volume: https://youtu.be/Jes5jwLl1q8?si=SZTtuHAEWKkNtNu-

    2. Second Volume: https://youtu.be/HS0mivVKLyo?si=WGrj0tXiB05N9nGZ

    3. Third Volume: https://youtu.be/CQr4Dq8aPB4?si=iAqRRAlzycdsZ47C

    4. Fourth Volume: https://youtu.be/cFscZ9c0AIk?si=mGAL9921qBBDjk_F

- Worksheets are designed so to guide you through the process.

You will find useful information (including a breakdown of the playlists)
on the website of Prof. Rob Ghrist of UPenn, who developed the materials course:
https://www2.math.upenn.edu/~ghrist/BLUE.html

### Additional References {-}

The following books are highly recommended. If you find the style of the videos doesn't fit 
you and would love to have something concrete to read, they are your friends.

1. Active Calculus: Multivariable by Schlicker et al. 2018 edition.
   (https://activecalculus.org/multi/preface-2.html)

1. Thomas' Calculus: Early Transcendentals by Hass, Heil, et al. $14^{th}$ edition.

1. Calculus Early Transcendental by Stewart. $8^{th}$ edition.

1. Anything you can find on Google would work. 
    Calculus is a subject that people have written about
    so much. So, there's no excuse for not having access 
    to the knowledge.

1. 3-D grapher: https://www.math3d.org/

1. Very good graphers: https://www.desmos.com/, https://www.geogebra.org/

### Course description  {-}
How do we describe the trajectory of a space shuttle? How is the human body affected by
scuba diving to different depths for different lengths of time? The mathematics required to
describe most real life systems involves functions of more than one variable. The concepts
of the derivative and integral from a first course in calculus must therefore be extended to
higher dimensional settings. In this course students will be guided through the essential ideas
of multivariable calculus, including partial derivatives, multiple integrals and vector calculus,
and their applications. These mathematical tools are used extensively in the physical sciences
and engineering, and in other areas including economics and computer graphics.

### Learning objectives {-}
After the course, students are expected to:

- Be confident in handling functions of two or more variables and familiar with how
they can be represented graphically

- Understand the key concepts of multivariable calculus, including partial derivatives,
the gradient vector, multiple integrals, line and surface integrals, the divergence and
curl of a vector function

- Know how such derivatives and integrals are calculated and some of their uses

- Be able to apply these ideas to real world problems

- Have improved analytic, computational and problem solving skills

## Assessment {-}
 
During the course, students are expected to compute their own percentage
points based on the following scheme.
The instructor is not responsible for providing the running percentage.

| **Form of assessment**      | **Weight**  |
|:---------------------------:|:-----------:|
| Weekly homework             | 40%         |
| Daily quizzes               | 10%         |
| Midterm                     | 20%         |
| Final                       | 30%         |

The following is the non-negotiable letter grade breakdown. It is based on
common practice in the United States for standard courses such as Calculus.

| **Letter Grade**        | **Percentage**      |
| :---------------------: | :-----------------: |
| A                       | [93,100]          |
| A-                      | [90,93)           |
| B+                      | [87,90)             |
| B                       | [83,87)             |
| B-                      | [80, 83)            |
| C+                      | [77,80)             |
| C                       | [73,77)             |
| C-                      | [70,73)             |
| D+                      | [67,70)             |
| D                       | [60, 66)            |
| F                       | [0,60)              |

## Core content {-}

1. Introduction
- Functions of two variables
- Graphs in three dimensions, surfaces and level curves
- Functions of three or more variables
- Limits and continuity
- Vectors (review)

2. Partial Derivatives
- Partial derivatives
- Tangent planes, linear approximations and differentials
- Chain rule
- Directional derivatives and gradient vectors
- Extrema and optimization
- Lagrange Multipliers

3. Multiple Integrals
- Double integrals
- Double integrals in polar coordinates
- Triple integrals
- Triple integrals in cylindrical and spherical coordinates
- Applications of multiple integrals

4. Vector Calculus
- Vector functions and their derivatives
- Vector fields
- Line integrals
- The fundamental theorem of line integrals
- Green’s Theorem
- Parametric surfaces and surface integrals
- Curl and divergence
- Divergence Theorem
- Stokes Theorem


## Late assignments {-}

- 15% of the possible total mark will be deducted for every 24 hrs (or part of 24 hrs) after the
deadline. Work more than 2 days late will not be accepted. 
- Except for exceptional circumstances (see [definition](https://onestop.fulbright.edu.vn/s/article/Exceptional-Circumstance)), 
  I will not extend the deadlines.

## Time expectations {-}

Some materials require time to be accustomed to. Some students are quicker than
others. However, on average, you should expect 10-15 hours per week (including class time)
on the materials in order to know the subject relatively well.

### Collaboration & Plagiarism {-}

Plagiarism is the act of submitting the intellectual property of another person as your own. It is one of the most serious of academic offenses. Acts of plagiarism include, but are not limited to:

* Copying, or allowing someone to copy, all or a part of another person's work and presenting it as your own, or not giving proper credit.

* Purchasing a paper from someone (or a website) and presenting it as your own work.

* Re-submitting your work from another course to fulfill a requirement in another course.

Further details can be found in the Code of Academic Integrity [[link](https://fulbright.edu.vn/articles/Code%20of%20Academic%20Integrity/Code%20of%20Academic%20Integrity_%20Excom%20Endorsed.pdf)].


## Learning Support {-}

In addition to your course instructors, there are other resources available to support your
academic work at Fulbright, including one-on-one consultations with learning support staff,
supplementary workshops, and both individual and group tutoring and mentoring in course
content, language learning, and academic skills. If you would like to request learning support,
please contact Fulbright Learning Support (https://learning-support.notion.site).

## Wellbeing {-}

Mental health and wellbeing are essential for the success of your academic journey. The
Fulbright Wellness Center provides various services including counseling, safer community,
and accessibility services. If you are experiencing undue personal or academic stress, are
feeling unsafe, or would like to know more about issues related to wellbeing, please contact
the Wellness Center via wellness@fulbright.edu.vn or visit the Wellness Center office on
Level 5 of the Crescent campus.

For more information, pleaes check 
https://onestop.fulbright.edu.vn/s/article/Health-and-Wellness-Introduction

\newpage

## Tentative Course Schedule {-}

The following schedule will be updated as we go so that students will know what to watch/read
before/after class.

| Week  | Topcs                                                                                                     | Watch                                  |
| ----- | --------------------------------------------------------------------------------------------------------- | -------------------------------------- |
| 1     | lines, planes, surfaces, coordinates, vectors; dot, cross, & scalar triple products                       | Vol 1: Chapters 1,2,3,4                |
| 2     | intro to vector calculus                                                                                  | Vol 1: Chapters 5,6,7,8                |
| 3     | motivating matrices, matrix algebra, linear systems, & row reduction, inverses                            | Vol 1: Chapters 9,10,11,12,13          |
| 4     | linear transformations & bases, determinants                                                              | Vol 1: Chapters 14, 15, 16, 17, 18     |
| Break | Tet (Feb 5 - 23)                                                                                          |                                        |
| 5     | multivariate functions & partial derivatives, derivatives as linear transformations                       | Vol 2: Chapters 1, 2, 3, 4             |
| 6     | derivatives as linear transformations, chain rule, derivative rules, inverse & implicit function theorems | Vol 2: Chapters 5, 6, 7, 8             |
| 7     | gradients, tangents, & linearization, multivariate Taylor expansion                                       | Vol 2: Chapters 9, 10, 11, 12, 13      |
| 8     | Applications: Optimization                                                                                | Vol 2: Chapters 14, 15, 16, 17, 18     |
| 9     | Integrals, Riemann sums                                                                                   | Vol 3: Chapters 1, 2, 3, 4, 5          |
| 10    | Applications: Mass & Probability                                                                          | Vol 3: Chapters 6, 7, 8, 9, 10, 11, 12 |
| 11    | Changing coordinates                                                                                      | Vol 3: Chapters 13, 14, 15, 16, 17, 18 |
| 12    | Path integrals                                                                                            | Vol 4: Chapters 1, 2, 3, 4, 5          |
| 13    | Differential forms & Fundamental theorems                                                                 | Vol 4: Chapters 6, 7, 8, 9, 10, 11, 12 |
